package com.sellivu.backend.settlement.domain;

public enum IssueExplanationCode {
    BENEFIT_SETTLEMENT_POSSIBLE,
    DAILY_POLICY_ADJUSTMENT_POSSIBLE,
    BIZ_WALLET_OFFSET_POSSIBLE,
    SAFE_RETURN_CARE_POSSIBLE,
    FAST_SETTLEMENT_POSSIBLE,
    PREFERRED_FEE_REFUND_POSSIBLE,
    SETTLEMENT_METHOD_REVIEW_REQUIRED,
    CONTEXT_OPTION_REVIEW_REQUIRED
}