package com.sellivu.backend.settlement.domain;

public enum SettlementIssueType {
    ORDER_ROW_UNMATCHED,
    FEE_ROW_UNMATCHED,
    SETTLEMENT_AMOUNT_MISMATCH,
    COMMISSION_AMOUNT_MISMATCH,
    NET_AMOUNT_MISMATCH,
    DUPLICATE_CANDIDATE,
    MISSING_JOIN_KEY,

    DAILY_ROW_MISSING,
    DAILY_ROW_DUPLICATED,
    DAILY_AMOUNT_MISMATCH
}